# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.20.1
	# for kotlin for fabric ?
	minecraft=1.20.1
	yarn_mappings=1.20.1+build.1
	
	fabric_loader_version=0.18.4
	enabled_platforms=fabric,forge
	architectury_version=9.2.14
	forge_version=1.20.1-47.4.10

# Mod Properties
	mod_version = 1.20.1-0.1.0
	maven_group = com.samsthenerd.hexgloop
	archives_base_name = hexgloop
	modID = hexgloop

# Dependencies
	fabric_version=0.92.7+1.20.1
	rei_version=12.1.785
	cloth_config_version=11.1.136

	wnboiVersion=0.1.0b

	# Hexcasting dependencies
	hexcastingVersion=0.11.3
	#As in https://maven.blamejared.com/at/petra-k/paucal/
	paucalVersion=0.6.0-pre-5
	patchouliVersion=84.1
	pehkuiVersion=3.8.2
	cardinalComponentsVersion=5.2.1
	serializationHooksVersion=0.3.24
	entityReachVersion=2.3.0
	lithiumVersion=mc1.20.1-0.11.4
	gravityApiVersion=1.0.9
	jeiVersion=15.20.0.129
	curiosVersion=5.14.1+1.20.1
	trinkets_version=3.7.2

	hexalVersion=0.3.1
	moreIotasVersion=0.1.1
	# because modrinth doesn't like multiple versions with the same name
	hexalVersionForge=PmrRTYFS
	moreIotasVersionForge=zrmwDsEQ
	geckolibVersion=4.8.2

	sodiumVersion=mc1.20.1-0.5.13-fabric

	kotlinForForgeVersion=4.12.0
	kotlin.stdlib.default.dependency = false
	asm_version = 9.4

	jetbrainsAnnotationsVersion=23.0.0

	#cc_version=v1.19.1-1.101.2-ccr
	#cct_version=1.101.2
	mixinExtrasVersion=0.5.3
	tooltipfixVersion=B2L4LeMV


systemProp.http.proxyHost=172.29.1.2
systemProp.http.proxyPort=995
systemProp.https.proxyHost=172.29.1.2
systemProp.https.proxyPort=995
org.gradle.daemonrg.gradle.java.home=C:\\Users\\Leon\\.jdks\\temurin-21.0.6\\
org.gradle.daemon=false
